"""empty message

Revision ID: 4c4d27a6cdb
Revises: 1360d1d3d39
Create Date: 2015-03-07 13:46:17.986436

"""

# revision identifiers, used by Alembic.
revision = '4c4d27a6cdb'
down_revision = '1360d1d3d39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
