"""empty message

Revision ID: 60faa60f2f
Revises: 4c4d27a6cdb
Create Date: 2015-03-07 13:47:34.600120

"""

# revision identifiers, used by Alembic.
revision = '60faa60f2f'
down_revision = '4c4d27a6cdb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
